### ISSUE TITLE
data is summarized by prepare_ma and no longer contains covariates at this point of prepare_prior

### ISSUE THREAD

**Issue by roboton** [wwiecek/baggr#113]
https://github.com/wwiecek/baggr/blob/e186fe8cbe3d5bc239d33f4b8b22c914c4527869/R/auto_prior.R#L224

I am trying to run an individual meta-analysis model with covariates and get an error because covariates can't be set since the `data` has been overwritten by a summary aggregate which no longer contains the individual level covariate.

@mattlowes

**Comment by wwiecek** [comment]
Hi @roboton and @mattlowes thank so much for bringing this up and sorry to get back to you late. The summary of individual data behaviour has been updated in the last 2 versions so very likely it just needs a simple fix, I will try to get to this soon.

**Comment by wwiecek** [comment]
I think this is now fixed in #114 which is pending checks and submission to CRAN in a few weeks. You can install from `devel` branch in the meantime if you want to fit models.

**Comment by roboton** [comment]
Thank you for all your work on baggr! cc'ing my coauthors who would be
excited to hear of this fix. @Raissa Fabregas ***@***.***>
 and @Giulia Zane ***@***.***>.

Appreciate the support!

Best, Rob

**Comment by wwiecek** [comment]
Thanks. Please say hi to Raissa from me!
