### ISSUE TITLE
remove quantreg dependency

### ISSUE THREAD

**Issue by homataheri** [wwiecek/baggr#117]
Today I experienced this error message while installing the baggr package.

![Screen Shot 2021-12-12 at 08 28 55](https://user-images.githubusercontent.com/76602959/145714249-f6edac5d-92b2-4423-bd55-1373e80fcfcd.png)

**Comment by wwiecek** [comment]
Thanks, looks like purely a `quantreg` installation issue. I'd recommend trying to install it first (`install.packages("quantreg")` will not require compilation of package from source). You may need to move to R version 4. Then installing baggr. Please let me know how that goes. The next version of `baggr` may remove dependence on quantreg package as it is currently not needed.

**Comment by homataheri** [comment]
Thank you, Witold. I just started learning R last week, so there are many unknowns to me.
I realized that I need to install R, before working with R-Studio. I installed R and then installed the baggr, and it worked.

Thank you again for this great work.

**Comment by wwiecek** [comment]
Glad it worked, good luck with R! Please me know if you run into any trouble.

I will use this GitHub issue as a reminder to remove `quantreg` dependency in the future
