### ISSUE TITLE
Rubin Model Speed

### ISSUE THREAD

**Issue by be-green** [wwiecek/baggr#16]
The Rubin Model is quite slow compared to a stripped down version.

At first I thought there might be overhead (depending on the implementation) from the if-else statements that are embedded in the current implementation of the model. At the same time, the Stan manual says that if-else is lazily evaluated so it shouldn't be a huge performance overhead (at least not relative to the time it takes to sample).

Just to compare, there's the current model:
```{stan output.var = 'current_model'}

data {
  int<lower=0> K; // number of sites
  real tau_hat_k[K]; // estimated treatment effects
  real<lower=0> se_tau_k[K]; // s.e. of effect estimates
  int pooling_type; //0 if none, 1 if partial, 2 if full
  real prior_upper_sigma_tau;
  real prior_tau_mean;
  real prior_tau_scale;
}
transformed data {
  int K_pooled; // number of modelled sites if we take into account pooling
  if(pooling_type == 2)
    K_pooled = 0;
  if(pooling_type != 2)
    K_pooled = K;
}
parameters {
  real tau;
  real<lower=0> sigma_tau;
  vector[K] eta;
  real tau_k[K_pooled];
}
transformed parameters {
  vector[K] theta = tau + sigma_tau * eta;        // school treatment effects
}
model {

  if(pooling_type == 0){
      // we don't care about the other parameter, let it wander!
      // but in that case we need to give a sensible prior for individual tau's and their SE's?
      tau ~ normal(0, 1); //wander tau but avoid divergent transitions
      tau_k ~ normal(prior_tau_mean, prior_tau_scale); //tau_k 'take on' tau's prior
      tau_hat_k ~ normal(tau_k, se_tau_k);
  }
  
  if(pooling_type == 1){
      tau ~ normal(0, 5); // prior on mean
      se_tau_k ~ cauchy(0,5); // prior on se
      tau_hat_k ~ normal(theta, se_tau_k);
  }
  
  if(pooling_type == 2){
      tau ~ normal(prior_tau_mean, prior_tau_scale);
      tau_hat_k ~ normal(tau, se_tau_k);
    }
  
}
```

After some testing (that I will leave aside), I think the issue is the inclusion of a parameter that the model does not actually use. In your model, you include $tau_k$ as a parameter no matter which model you are evaluating. For whatever reason it _really_slows things down. Compare the performance of these two models:

```{stan output.var = partpooled_stripped_down}
data {
  int<lower=0> K; // number of sites
  real tau_hat_k[K]; // estimated treatment effects
  real<lower=0> se_tau_k[K]; // s.e. of effect estimates
}
parameters {
  real tau;
  real<lower=0> sigma_tau;
  vector[K] eta;
  
}
transformed parameters {
  vector[K] theta = tau + sigma_tau * eta;        // school treatment effects
}
model {
  tau ~ normal(0, 5); // prior on mean
  eta ~ normal(0,1); // implies theta ~ normal(tau,sigma_tau)
  se_tau_k ~ cauchy(0,5); // prior on se
  tau_hat_k ~ normal(theta, se_tau_k);
}
```

```{stan output.var = partpooled_extra_param}

data {
  int<lower=0> K; // number of sites
  real tau_hat_k[K]; // estimated treatment effects
  real<lower=0> se_tau_k[K]; // s.e. of effect estimates
}
parameters {
  real tau;
  real<lower=0> sigma_tau;
  vector[K] eta;
  real tau_k[K];

}
transformed parameters {
  vector[K] theta = tau + sigma_tau * eta;        // school treatment effects
}
model {
  tau ~ normal(0, 5); // prior on mean
  eta ~ normal(0,1); // implies theta ~ normal(tau,sigma_tau)
  se_tau_k ~ cauchy(0,5); // prior on se
  tau_hat_k ~ normal(theta, se_tau_k);
}

```

```{r}
test_data <- list(
  K = 8,
  tau_hat_k = schools$tau, # same as y
  se_tau_k = schools$se # same as sigma
)


times <- microbenchmark::microbenchmark(
  current_fit <- sampling(no_else_partpooled, data = test_data),
  ifelse_fit <- sampling(partpooled_extra_param, data = test_data),
  times = 1)
```

This is the ouput
```
> print(times)
Unit: seconds
                                                             expr
    stripped_down <- sampling(partpooled_stripped_down , data = test_data)
 extra_param <- sampling(partpooled_extra_param, data = test_data)
      min       lq     mean   median       uq      max neval
  1.51534  1.51534  1.51534  1.51534  1.51534  1.51534     1
 34.19129 34.19129 34.19129 34.19129 34.19129 34.19129     1

```

**Comment by wwiecek** [comment]
Hi, thanks for checking this! You can see that there is no slow down in baggr, i.e. this runs fast:
```
library(baggr)
baggr(schools)
baggr(schools, pooling="none")
baggr(schools, pooling="full")
```

In my code `tau_k` is of dimension 0 if there's full pooling, see `rubin.stan`:18-22

Your example is slow not because it contains superfluous parameters, but because they are unconstrained. If you do `tau_k ~ normal(0,1)` then there is no slowdown.
There is one case in my code where we have such extra parameter: in case of no pooling we let tau wander as normal(0,1) (`rubin.stan`:35). It's probably not a good practice but I'm happy to keep it as-is until I see it causing problems.

**Comment by be-green** [comment]
Oh, it must have happened during the reparameterization because tau_k no longers matters for the model (it all depends on theta). So you suggest just putting a prior on tau_k for the partial pooling model to help constrain it?

**Comment by wwiecek** [comment]
Tau_k already has a distribution in the partial pooling model. To summarise:

1 I imagine for almost any model if we add superfluous parameters with no
priors, convergence will be poor.
2 That is not the case for partial pooling, because tau_hat_k, tau_k and
tau all have sensible distributions.
3 For model with no pooling tau_k is set to dimension 0 so there is no
problem either.
4 For model with full pooling tau has no interpretation, so we have to do
something to avoid case 1. I put tau ~ normal(0,1) and so far had no
problems.

Case 4 is the only one that needs to be examined.

**Comment by be-green** [comment]
Hey, sent you an email too, but tau_k no longer has a sensible distribution in my reparameterized model. This might not be an issue in your implementation and could probably be fixed with some proper labeling.
