### ISSUE TITLE
mutau model crashes R session

### ISSUE THREAD

**Issue by be-green** [wwiecek/baggr#18]
I was trying to figure out how to work with the various models and I found that when I ended up repeatedly crashing my R session. As a test I ran prepare_ma with the simplified microcredit dataset, and when I plugged that into the mutau model it began sampling and then crashed. Here's my code:

```
mt_data <- prepare_ma(microcredit_simplified, outcome = "consumerdurables")
baggr(mt_data)
```

Sometimes it crashes right away and sometimes later. This seems like an issue on the Stan side since it's crashing during sampling.

Not really sure whether it's something on my end or not, but if it is then it would be nice to have an error instead of crashing the session.

Session Info:

R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils    
[5] datasets  methods   base     

other attached packages:
[1] baggr_0.0.0.9000 Rcpp_1.0.1      

loaded via a namespace (and not attached):
 [1] pillar_1.4.1       compiler_3.6.0    
 [3] plyr_1.8.4         prettyunits_1.0.2 
 [5] tools_3.6.0        packrat_0.5.0     
 [7] bayesplot_1.7.0    pkgbuild_1.0.3    
 [9] tibble_2.1.3       gtable_0.3.0      
[11] lattice_0.20-38    pkgconfig_2.0.2   
[13] rlang_0.3.4        Matrix_1.2-17     
[15] cli_1.1.0          rstudioapi_0.10   
[17] parallel_3.6.0     SparseM_1.77      
[19] loo_2.1.0          gridExtra_2.3     
[21] dplyr_0.8.1        stringr_1.4.0     
[23] MatrixModels_0.4-1 stats4_3.6.0      
[25] grid_3.6.0         tidyselect_0.2.5  
[27] glue_1.3.1.9000    inline_0.3.15     
[29] R6_2.4.0           processx_3.3.1    
[31] rstan_2.18.2       callr_3.2.0       
[33] ggplot2_3.1.1      purrr_0.3.2       
[35] reshape2_1.4.3     magrittr_1.5      
[37] codetools_0.2-16   matrixStats_0.54.0
[39] StanHeaders_2.18.1 ps_1.3.0          
[41] scales_1.0.0       ggridges_0.5.1    
[43] fortunes_1.5-4     rstantools_1.5.1  
[45] assertthat_0.2.1   colorspace_1.4-1  
[47] quantreg_5.40      stringi_1.4.3     
[49] lazyeval_0.2.2     munsell_0.5.0     
[51] crayon_1.3.4

**Comment by be-green** [comment]
It seems to consistently crash as soon as warmup ends (after the 1001 draw). I'll do more testing, but I can't find an existing issue with rstan that covers this. It looks like the full pooling model works fine but the partial and no-pooling models break.

**Comment by EdJeeOnGitHub** [comment]
When you run `baggr` with `chains = 1, verbose = TRUE` do you get any error output or does it still just crash the R session?

**Comment by be-green** [comment]
I don't get any error output. This is what it looks like.

![image](https://user-images.githubusercontent.com/23174585/61337996-2cb2f180-a7fd-11e9-8725-f3c42dc3f79e.png)

Is there a way to save a log file of some kind?

**Comment by be-green** [comment]
Attached are my attempts at a log file using the sample_file argument. It looks like it just fails to create samples altogether... The diagnostic log had the same output.

[sampling.log](https://github.com/wwiecek/baggr/files/3399549/sampling.log)
[diagnostic.log](https://github.com/wwiecek/baggr/files/3399550/diagnostic.log)

**Comment by EdJeeOnGitHub** [comment]
Forgive me if you've already done this, but have you tried running `pkgbuild::has_build_tools(debug = TRUE)` (this should return TRUE) and checking that the C++ toolchain is correctly installed?

**Comment by be-green** [comment]
I haven't, but the other models all work for me. This is just the mutau model for me, the rubin and quantiles models work fine. I have RTools installed, I can run my own stan models, I can run these stan models, and compile the package just fine.

pkgbuild::has_build_tools(debug = TRUE) returns true. So does has_rtools, etc.

**Comment by EdJeeOnGitHub** [comment]
That is very strange.

I thought maybe it could be the sufficient statistic function causing problems but that's not even in the mutau model. 

I don't have access to a Windows machine so I can't really replicate this either, I'm afraid. 

I believe Rachel uses a mac and I'm not sure about Witold so it's possible this is a Windows specific issue and you're the first to come across it. :(

**Comment by wwiecek** [comment]
Hi both,

* It doesn't replicate for me.
* We have consistently tested on Windows so it's not OS specific. 
* FYI, the way that error occurs ("R session aborted") is typical for compiled code error (i.e. for many packages that run C++/C code). If you run R from command line it will be less dramatic but you will also see R crash.
* Crash when going into warmup would also indicate Stan problems rather than anything else

Random guess would be that maybe the models do not compile correctly in 3.6 with the version of RTools that you have. 

I will keep this open for now, as a reminder for when we next test the "mutau" models (they are not included in the v0.1 release on CRAN) but for now I don't have an answer.

**Comment by be-green** [comment]
Yeah that's what I was thinking too! I'll download an earlier version of R and test. I've never seen this with any stan models, couldn't figure out anything wrong with the code, and can't find anyone else who has had the issue with stan (in any package or rstan or cmdstan). If no one else can replicate then it is probably a low priority issue, I just figured it was good to flag!

**Comment by be-green** [comment]
Ok, so I rebuilt the package in 3.4.4 and got a much more informative error message--the dimensions of one of the prior objects in the standata list didn't match what Stan expected. Perhaps there's a dev version that I don't have access to that makes this work? I'm pretty sure my build is current with the master.

I broke my 3.4.4 install as I did this so I'll try to remedy that and post the details once I can.

**Comment by wwiecek** [comment]
Hi Brice, thanks if you can share the log but indeed this is lower priority
so please don't waste much of your time on this - I'd feel bad for you as
it won't be another few weeks at minimum that I'll look at this model
again.

**Comment by wwiecek** [comment]
@be-green after testing the package and reading about Stan 2.18 bugs I think your problem may be solved by upgrading to Stan 2.19 (try with R >= 3.5.3); error in R 3.4.4. that you reported might be something else (it's also possible that I broke `mutau` a few days ago while fixing some priors, as the tests for that model are disabled right now)

Please let us know if you have a chance to look into this.

**Comment by be-green** [comment]
Sounds good, I'll post an update once I get a chance to test.

**Comment by be-green** [comment]
Updated my rstan version and a number of my other packages, cleaned up my install, and it's working just fine! Or at least it isn't crashing my R session...

![image](https://user-images.githubusercontent.com/23174585/61667670-40000a00-aca0-11e9-9df9-53e0fefcb445.png)
