### ISSUE TITLE
8 schools checks of correctness

### ISSUE THREAD

**Issue by wwiecek** [wwiecek/baggr#22]
@be-green had a check for correctness for the Rubin model that used 8 schools result (it worked fine), I hope he can add it as a pull request before end of Oct

**Comment by be-green** [comment]
I've finished implementing that test, it should be in my current pull request. I'm trying to fix it, but I'm running into build issues on my local machine, so I'm going to have to likely re-install the whole C++/RTools setup and might need to reset my R/Rstudio. I'll flag this for closing this once that's accepted.

**Comment by wwiecek** [comment]
@be-green Sorry, can you let me know where it is exactly? I only see the test for loo, but I thought there would be another test against a matrix of school-specific means (for no pooling, partial, full). 
I guess LOO being same as in publications is almost definitely sufficient condition for the estimates of school-specific means to match, but it's good to test for it separately, because the reverse does not hold.

**Comment by be-green** [comment]
Yeah, I'll break it out as a separate testing script to make it clearer. I didn't include tests for no pooling and full pooling, but I can throw that in pretty easily.

**Comment by be-green** [comment]
@wwiecek I just pushed to the same branch with a version that breaks out the 8 schools check vs. brms. I haven't added no-pooling and full-pooling versions since I think those are pretty straightforward models. I can fit those and add a unit test if you think it's necessary.

**Comment by wwiecek** [comment]
This is done. I increased tolerance 20% as on one of the servers the results didn't match that closely.
