### ISSUE TITLE
order=FALSE does not work in baggr_compare?

### ISSUE THREAD

**Issue by wwiecek** [wwiecek/baggr#24]

**Comment by wwiecek** [comment]
@be-green I'm going through old issues. Have you seen this? Maybe this could be part of the baggr_compare PR you were working on? It's very low priority, though

**Comment by be-green** [comment]
I can add functionality and a test for that.

**Comment by be-green** [comment]
This is now added in the pull request. I left the argument in the ... as it was before. I can specify it as a parameter if that's preferable. Up to you @wwiecek .

**Comment by wwiecek** [comment]
Brilliant, I will close this once I reviewed and merged the whole PR.

**Comment by wwiecek** [comment]
@be-green I tried `order=TRUE` with `plot(baggr_compare())`. Unfortunately I got this:

![image](https://user-images.githubusercontent.com/20645798/75054942-ff819c80-54cb-11ea-8504-6c5a3317e4da.png)

Let me know if you prefer to have a look at this, I'm happy to do it but giving you first dibs!

**Comment by be-green** [comment]
OOH that's weird, I will look! Can you send me the code?

**Comment by be-green** [comment]
I guess this is why we have devel branches!

**Comment by wwiecek** [comment]
Don't mention the long generation code, it's irrelevant, i.e. taken from other tests:

```
schools_ipd <- data.frame()
N <- c(rep(100, 4), rep(200, 4))
for(i in 1:8){
  x <- rnorm(N[i])
  x <- (x-mean(x))/sd(x)
  x <- x*schools$se[i]*sqrt(N[i])/1.41 + schools$tau[i]
  
  y <- rnorm(N[i])
  y <- (y-mean(y))/sd(y)
  y <- y*schools$se[i]*sqrt(N[i])/1.41
  
  schools_ipd <- rbind(schools_ipd,
                       data.frame(group = schools$group[i], outcome = x, treatment = 1),
                       # This is just so that we don't trip off prepare_ma:
                       data.frame(group = schools$group[i], outcome = y, treatment = 0))
}

prepare_ma(schools_ipd) #similar SEs, different means, obvs
summ <- prepare_ma(schools_ipd)
schools_ipd %>% group_by(treatment, group) %>% summarise(sd(outcome))
summ$se <- summ$se.tau; summ$mu <- NULL; summ$se.mu <- NULL; summ$se.tau <- NULL
# group_by(schools_ipd, group, treatment) %>% summarise(sd(outcome))

w1 <- baggr(schools_ipd)
w2 <- baggr(summ)
bgc <- baggr_compare(w1, w2)
plot(bgc, order = TRUE)
```

**Comment by be-green** [comment]
Thanks, I'll take a look now.

**Comment by be-green** [comment]
This issue seems to be that the mint() command isn't picking up the correct model name in this case. Not sure why, I'm still investigating. In one case it returns a matrix, in one case it returns a vector. 
![image](https://user-images.githubusercontent.com/23174585/75056399-8f0f5700-549c-11ea-9093-de925b6b52d2.png)

This is making it drop the name from `Model 1`, and thus it isn't getting passed to print and plotting functions. Is there a reason for this behavior?

**Comment by wwiecek** [comment]
Ah, I see! Glad we spotted this bug. `treatment_effect()` behaves differently for full data models.

I will fix it. But in the meantime I think you should not depend on that piece of code to store model name? Cause it's not a planned feature of it. All of the group labels, model names etc. you can access directly in `baggr` object structure.

**Comment by wwiecek** [comment]
Another reason for not depending on `treatment_effect` behaviour is that actually its dimensionality (and whether it's vector, matrix or array) might change once we have quantiles modelling (because reasons). So I will need to rewrite a lot of code that calls on trt effect function anyway.

**Comment by be-green** [comment]
Ok, so I shouldn't call on treatment_effect at all in baggr compare? I thought we'd previously discussed that I should default to using it... but maybe I'm just confusing a conversation about the predict.R branch.

**Comment by wwiecek** [comment]
No, no, you should call on it! But you were talking about model names. `treatment_effect` is only designed to return values (vector or matrix).
If the problem is in that you want to treat that 1-row matrix as a vector, for now I'd wrap it in c(). That converts matrix row to a vector (dropping colnames).

**Comment by be-green** [comment]
I wasn't using treatment_effect to store names. I was calling `treatment_effect` across each model, and then using `rbind()` to combine the outputs of the mean treatment or sd of treatment effects. In the case where one element in `rbind` is a vector and the other is a matrix, it drops rownames, and thus the names of the models being stored in the list.

**Comment by wwiecek** [comment]
ah, yes, so I'd just convert them all to vectors length 3, with no names even, then manually set the names after rbinding, just to be super-safe

**Comment by wwiecek** [comment]
Seems that this is fixed in the latest version already, closing.
