### ISSUE TITLE
Check consistent use of hypervariance vs hyper-SD

### ISSUE THREAD

**Issue by wwiecek** [wwiecek/baggr#30]

**Comment by rmeager** [comment]
We want to move everything to hypersd in all our documentation and vignette, correct? I can do this today if yes. Currently I see a mix of hypervar and hypersd.

**Comment by rmeager** [comment]
Oh wait, I see the distinction you've made between hypervar (for mutau) and hypersd (all else) in the baggr function documentation. I can / have started cleaning up the rest of the documentation and vignette to align with that, but let me know if you'd rather move everything to hypersd terminology.
