### ISSUE TITLE
Add predict. methods and pp_check()

### ISSUE THREAD

**Issue by wwiecek** [wwiecek/baggr#34]
The idea is to do a posterior predictive check against the original input data. That means

* `predict()` function that returns new draws for original data
* `pp_check()` function that visualises this (using `bayesplot` functionality)

The first pass at it (thanks to Brice) is in `devel-predict`. It works nicely with Rubin model, but 

* doesn't work with mu & tau model
* lacks some documentation
* does not have tests 
* does not pass checks (S3)

**Comment by be-green** [comment]
I'm working on this as we speak! Hopefully something functional by the end of the month now that I have more time post-holidays...

**Comment by wwiecek** [comment]
Thanks!

**Comment by wwiecek** [comment]
`predict()` and `pp_check()` are now included for Rubin model in v0.4, but some documentation is still needed, as it is not explained what do these methods do, no examples are given; 

I updated the S3 method to pass the checks, but haven't checked test coverage

**Comment by be-green** [comment]
@wwiecek  Do we have notation for pull requests that just include docs or tests or hotfixes? Or are they all just devel-whatever?

**Comment by wwiecek** [comment]
`devel-whatever` I think, because this would be merging to `devel`?

**Comment by wwiecek** [comment]
but happy to discuss a naming strategy for the future!

**Comment by wwiecek** [comment]
So currently this is working for Rubin but not for other models, right?

**Comment by be-green** [comment]
Yup!
