### ISSUE TITLE
Refresh LOO CV part of the vignette.

### ISSUE THREAD

**Issue by wwiecek** [wwiecek/baggr#35]

**Comment by wwiecek** [comment]
@be-green we discussed this informally, the goal would be to read the vignette and nicely describe the tweaks you made to `loocv()`... You can harmonise that text with your `?loocv`. Once you're happy with it, I will review.

* You need to update the example in `?loocv` too, the "attributes" part is wrong.
* You should add a Gelman reference in `?loocv`
* The rounding of values is not good, at the moment, I just ran a comparison of full vs partial pooling and got ELPD of "-14" for both... So I can't pick the best! Maybe you need more digits or a rule which gives you more/less digits depending on magnitude of ELPD?

**Comment by be-green** [comment]
This all sounds reasonable, I'll try to make those changes this weekend. The rounding sounds especially glaring! I'll take a look.

**Comment by be-green** [comment]
I'm also adding a loo_compare method (similar to [this](https://mc-stan.org/loo/reference/loo_compare.html)). I'll hopefully have a pull request in soon.

**Comment by be-green** [comment]
@wwiecek which Gelman reference did you want? The pull request is ready otherwise.

**Comment by wwiecek** [comment]
It is in PR review

**Comment by wwiecek** [comment]
@be-green can we close this? Or did you have plans to change LOO CV still? I dropped the ball on this because I moved into new models without reviewing LOO CV in Rubin model thoroughly. Let me know if there's something I could do.

**Comment by be-green** [comment]
As far as I remember this is done!
