### ISSUE TITLE
baggr_compare: hyper=T doesn't do anything

### ISSUE THREAD

**Issue by wwiecek** [wwiecek/baggr#40]
Currently `compare = c("groups", "effects")`, where `effects` is a "hypothetical study" (`effect_draw`).

I'd like to add:

* hypermeans (Basically show what is currently returned as first table)
* hypersds (second table)
* groups + hypermeans (what you would get with `baggr_plot(model, hyper=TRUE)`, but now for many models)

PS: And these tables need to be outputted differently, as per the other issue #29

**Comment by be-green** [comment]
@wwiecek, Perhaps I can take this along with the other baggr_compare PR?

**Comment by wwiecek** [comment]
If easy to do, then sure!

**Comment by wwiecek** [comment]
@be-green the idea was to have the same option in `baggr_compare` as you have in `baggr_plot`, i.e. `hyper=`; in your latest PR there is no control over this. Would it be possible to add `hyper=` option to `baggr_compare`?

**Comment by be-green** [comment]
Yes, I'll fix that.

**Comment by wwiecek** [comment]
Thanks!
When you have a look, can we also have the same ordering as in `baggr_plot`? i.e. group-effects on top, pooled estimate at bottom; it's a convention that forest plots typically use, hence I wanted to keep it that way

**Comment by be-green** [comment]
Yes, I'll move this to the bottom. I'll put this all into a pull request today (hopefully) and try to push the changes.

**Comment by wwiecek** [comment]
Thanks! Don't sweat it, though, this can wait until next release if you're pressed for time.

When you fix it, would be good to have it covered with unit tests (same as other arguments to `plot.baggr_compare`). 
Even if not doing eyeball/graphical tests, you can often access relevant properties of ggplot objects, I think? And if not, checking that anything at all renders (`expect_is(..., "gg")`) is good for the future.

**Comment by wwiecek** [comment]
PS: You can check where you're lacking unit test coverage [here](https://codecov.io/gh/wwiecek/baggr/src/679e4640e5a9579c454664d84fa2d4f1e775aefe/R/baggr_compare.R)

**Comment by be-green** [comment]
Ok, just implementing testing now. Fixed the bugs, made hyper = T do things, etc. Some of the stuff will need to be revisited or discussed, but it should work on the unit tests now at least. The only thing I'm actually worried about is the matrix vs. vector thing long-term. Maybe we can discuss how we expect `treatment_effect` to work in the long run on another forum or over skype?

**Comment by wwiecek** [comment]
Yes, we will, but only once the quantiles models are in, because reasons. It's a bit of domino, basically. I will let you know when I plan to change it.

**Comment by be-green** [comment]
This is fixed in the pull request I just submitted. Not sure how to tag it in here.

**Comment by wwiecek** [comment]
Yup, got it, will have a look

**Comment by be-green** [comment]
Just refactored some stuff too for better test coverage, let me know if you have questions or thoughts.

**Comment by wwiecek** [comment]
@be-green your tests fail, you can find check online here: https://travis-ci.org/wwiecek/baggr/

**Comment by wwiecek** [comment]
```
  1. Failure: baggr comparison method works for Full model (@test_binary.R#259) 
  2. Failure: baggr comparison method works for Full model (@test_binary.R#260) 
  3. Failure: baggr comparison method works for Full model (@test_full.R#85) 
  4. Failure: baggr comparison method works for Full model (@test_full.R#86) 
  5. Failure: baggr comparison method works for Rubin model (@test_rubin.R#337) 
  6. Failure: baggr comparison method works for Rubin model (@test_rubin.R#338) 
```

**Comment by be-green** [comment]
I guess that's what happens when you go too fast... I'll do more testing and push later then.

**Comment by be-green** [comment]
Alright, this should be fixed now. The "effect plots" needed different tests from the "group" plots because their plotting method returns a single plot instead of a list of plots.
