### ISSUE TITLE
Allow baggr_compare()'ison of covariates (fixed effects)

### ISSUE THREAD

**Issue by wwiecek** [wwiecek/baggr#50]
Once the next PR is done

**Comment by be-green** [comment]
Fixed effects meaning pooled treatment effects? Fixed effects (as a term) is confusing for economists because it refers to a non-parametric approach to estimating unobserved average differences between individuals! So kind of like random effects as most other people use it.

**Comment by wwiecek** [comment]
[Fixed effects as in fixed and random effects](https://stats.stackexchange.com/questions/4700/what-is-the-difference-between-fixed-effect-random-effect-and-mixed-effect-mode). But, yes, I know about this confusion and won't be using FE/RE without explanation in the package.

**Comment by wwiecek** [comment]
@be-green Is that in the current version?

**Comment by be-green** [comment]
Not sure what this means exactly, so I'm gonna say maybe but probably not? Is this in the case where we have covariates other than the randomly varying measurements?

**Comment by wwiecek** [comment]
Measurements themselves are not covariates. Don't worry about it, I'll add!

**Comment by wwiecek** [comment]
This is now in the v0.6.9, but the next step is to add `baggr_compare(strata = "covariate") type syntax, which also groups outputs by levels of a given covariate
