### ISSUE TITLE
Possible compilation issues in Windows 

### ISSUE THREAD

**Issue by be-green** [wwiecek/baggr#52]
I really don't know what's going on with all these models, but both MuTau and Logit now crash my R session. I'll post updates as I try to debug the behavior...

**Comment by be-green** [comment]
This is the code I ran to make it break. It starts sampling and then breaks.

# prepare_ma for binary data
df_pat2 <- data.frame(treatment = rbinom(900, 1, .5),
                      group = rep(paste("Trial", LETTERS[1:10]), each = 90))
df_pat2$outcome <- ifelse(df_pat2$treatment, rbinom(900, 1, .3), rbinom(900, 1, .15))

baggr(df_pat2)

My Makevars file is set according to the old rstan wiki advice:

CXX14 = g++ -std=c++1y
CXX14FLAGS = -mtune=native -march=native -O3
CXX11FLAGS= -O3 -march=native -mtune=native


Looks like they've recently changed that advice to be 

CXX14 = g++ -std=c++1y

CXX14FLAGS=-O3 -march=native -mtune=native
CXX11FLAGS=-O3 -march=corei7 -mtune=corei7

I'm going to rebuild `baggr` from scratch with this setup and see if it fixes anything.

**Comment by be-green** [comment]
Rebuilt with the new makevars but it still isn't working. The diagnostic file shows that sampling doesn't even start. Honestly I'm not sure what to do about this, @wwiecek if you have any insight I'd appreciate help.
[err.txt](https://github.com/wwiecek/baggr/files/4110400/err.txt)

**Comment by be-green** [comment]
It works when I compile the model in an interactive session, but still repeatedly crashes from the loaded object.

```
# this is fine
model <- rstan::stan_model("src/stan_files/logit.stan")

dat <- baggr::convert_inputs(df_pat2, model = "logit")
dat$pooling_type = 1
dat$prior_hypermean_fam = 1
dat$prior_hypermean_val = c(0,1)

dat$prior_hypersd_fam = 1
dat$prior_hypersd_val = c(0,8)

sampling(model, data = dat)
```

**Comment by be-green** [comment]
Update: when I install from CRAN that version also works fine. Must be an issue with my compiler.

**Comment by be-green** [comment]
Ok I changed my settings back to what they were, and used -march=corei7 instead of -march=native and that seemed to work. I'll recompile a few times and see if that's really what made the difference or if I got really lucky...

**Comment by be-green** [comment]
Yes, this is replicating, closing now.

**Comment by wwiecek** [comment]
I had similar problems and similar conclusions. This is likely a WIndows & Intel processors issue that has been mentioned by Stan devs in a few places. Likely changing CXX14FLAGS will have an impact, because the compiler tries to use C++ 14 standard. 
I will keep this open for a while longer.

**Comment by wwiecek** [comment]
> This is the code I ran to make it break. It starts sampling and then breaks.

BTW You need triple backticks when quoting code.

**Comment by be-green** [comment]
Fixed the formatting!

**Comment by wwiecek** [comment]
I changed `native` to `corei7` for my `.R/Makevars.win` and haven't had any crashes yet

Will keep this open for a while longer, just in case. I think there will be some `Makevar` changes (within package, i.e. `src/`) in the coming months, to do  with 2.19.3 and Rcppparallel

**Comment by be-green** [comment]
Yay! And that's a much better name. Previously I'd get random crashes with the mutau model--I can run both a bunch of times under the new settings and see if it's fixed.

**Comment by wwiecek** [comment]
Great. But I rewrote mutau model (not in devel yet) so best if you test in February.
