### ISSUE TITLE
Better display for covariates in print.baggr

### ISSUE THREAD

**Issue by wwiecek** [wwiecek/baggr#59]
![image](https://user-images.githubusercontent.com/20645798/75024318-1951be00-5491-11ea-933f-5bca27e162a8.png)

This doesn't even have the variable name

**Comment by be-green** [comment]
What branch is this for? I assume meta-regression?

**Comment by wwiecek** [comment]
Yes, but I will tackle this, it needs a few other changes that I didn't write up.

**Comment by wwiecek** [comment]
BTW branches need a bit of a clean-up

**Comment by be-green** [comment]
Ok, let me know how I can help.
