### ISSUE TITLE
plot.baggr_compare transformation is wrong

### ISSUE THREAD

**Issue by wwiecek** [wwiecek/baggr#62]
The hypermean does not seem to have the transformation applied e.g. when running baggr_compare for logOR model and trying to apply `transform = exp`

**Comment by wwiecek** [comment]
@be-green I don't imagine you have time but namechecking you just in case -- but don't worry otherwise, I will check this in the coming weeks

**Comment by be-green** [comment]
I am done with my masters the 19th, moved back from Texas the 24th, and then I'll have more time! Sorry, I've just been pulled in a million directions the last few months...

**Comment by wwiecek** [comment]
Very much the same for us in London! This was a way of saying hello from a far rather than a "real" request. If you have some time to spare please ping me, but definitely ignore until then. I might name check you here and there so that you have an idea where it would be nice to have help but totally don't feel obliged.
