### ISSUE TITLE
Pre-compute vignette objects and store them

### ISSUE THREAD

**Issue by wwiecek** [wwiecek/baggr#78]
Currently I run some `loocv` and `logit` models with `iter=500` but soon even this won't be enough. I could run and store outputs with `iter = 5000`

Could either store within package or at a stable online location (GitHub?)

**Comment by be-green** [comment]
Could we compute the stan models, store them via posteriordb and access them on github during the vignette compilation process?
https://github.com/MansMeg/posteriordb/tree/master/rpackage
That way we wouldn't need to run anything locally.

**Comment by wwiecek** [comment]
I don't see much of an advantage in that. Or rather, I think it's maybe a solution if we were sure we wanted to store the results somewhere, but I thought we agreed that the first solution was to check if it is possible to submit precompiled Markdown packages in such a way that CRAN will not run all of the (lengthy) code. That is the only issue, I think.

AFAIK CRAN does use the precompiled doc anyway, but runs the code to check for any errors. Or something like that.

**Comment by be-green** [comment]
That's fair, just a passing thought when I was reading about the package.

**Comment by wwiecek** [comment]
Sure -- didn't mean to shoot it down entirely!
